### ISSUE TITLE
Incorrect profiles path usage

### ISSUE THREAD

**Issue by AlekHed** [Toloka/dbt-af#19]
**Describe the bug**
Incorrect profiles path usage.

```
  File ".../python3.10/site-packages/dbt_af/dags.py", line 120, in compile_dbt_af_dags
    with open(config.dbt_project.dbt_project_path / 'profiles.yml') as fin:
```

In code above you can see dbt_project_path and profiles.yml are in path to open. It's not correct. Need to replace dbt_project_path with dbt_profiles_path.

**To Reproduce**
Just try to use profile.yml not in dbt project root and get error on run

**Expected behavior**
Use setting dbt_profiles_path from Config

**Comment by NikitaYurasov** [comment]
Hi! Thank you for this issue. It will be fixed in the next version `0.8.0`
